
modules-search: [ local ]

sequence:
- show:
  - welcome
  - locale
#  - licence
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - plymouthcfg
  - luksbootkeyfile
  - dracutlukscfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - dracut
  - grubcfg
  - bootloader
  - removeuser
  - packages
  # shellprocess
  - umount
- show:
  - finished
branding: {{branding}}
prompt-install: true
dont-chroot: false
