name: 10001-build-packages-debs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: 10001 Debian12 build packages debs
    runs-on: ubuntu-24.04
    timeout-minutes: 7200
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4
      - name: Setup nodejs 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: build packages debs
        run: |
          ./10001-run-build-packages-debs.sh
      - name: debs export
        uses: actions/upload-artifact@v4
        with:
          name: packages-debs-latest
          path: ./mychroot/ci/penguins-eggs_10*
          retention-days: 1
          if-no-files-found: warn
          compression-level: 0
          overwrite: true
          include-hidden-files: false          
      
